sed -i '/300.*whisper-trade/d' design/IN_PROGRESS.md
echo '- [x] `300` The Whisper Trade — `specs/300-whisper-trade.md` — completed 2026-03-06' >> design/COMPLETED.md
git add design/
git commit -m "feat(layer1): complete whisper trade system

Implements RED-GREEN-REFACTOR from spec 300:
- Added comprehensive test suite (RED phase)
- Implemented Secret, Broker, generate_secrets_system, execute_whisper_trade_system, paranoia_unrest_system (GREEN phase)
- Test coverage: 96.58% (target: 85%)

All acceptance criteria met:
- Secrets are generated by relevant jobs over time.
- Trading secrets increases a global paranoia metric.
- High paranoia correctly translates into pop-level unrest.
- cargo test passes
- cargo clippy clean

Co-Authored-By: google-labs-jules[bot] <161369871+google-labs-jules[bot]@users.noreply.github.com>"
