use super::Layer1SystemSet;
use crate::layer1::*;
use crate::layer1::social::old_guard::mood_lifecycle_system;
use bevy_ecs::prelude::*;

pub fn register(schedule: &mut Schedule) {
    schedule.add_systems(
        (
            consume_food_system
                .after(produce_food_system)
                .after(update_resource_caps_system),
            crate::layer1::drone::drone_battery_system.after(consume_food_system),
            clothing_wear_system.after(consume_food_system),
            vermin_growth_system.after(consume_food_system),
            vermin_effect_system.after(vermin_growth_system),
            vermin_morale_system.after(vermin_growth_system),
            crate::layer1::integration::vermin_item_rot_system.after(vermin_growth_system),
            spoilage_system
                .after(consume_food_system)
                .after(vermin_growth_system),
            crate::layer1::visitor::visitor_lifecycle_system.after(consume_food_system),
            theft_system
                .after(consume_food_system)
                .before(decay_needs_system),
            decay_needs_system.after(consume_food_system),
            crate::layer1::hygiene::filth_accumulation_system.after(decay_needs_system),
            crate::layer1::hygiene::hygiene_decay_system
                .after(crate::layer1::hygiene::filth_accumulation_system),
            crate::layer1::chemical::addiction_system.after(decay_needs_system),
            apply_palette_fatigue_system.after(consume_food_system),
            apply_cabin_fever_morale_system
                .after(decay_needs_system)
                .before(mood_lifecycle_system),
            faction_satisfaction_morale_bridge
                .after(apply_cabin_fever_morale_system)
                .before(mood_lifecycle_system),
            apply_taboo_stress_system
                .after(decay_needs_system)
                .before(mood_lifecycle_system),
        )
            .in_set(Layer1SystemSet::Consumption),
    );

    schedule.add_systems(
        (
            mood_lifecycle_system.after(decay_needs_system),
            trend_setting_system.after(consume_food_system),
            trend_spread_system.after(trend_setting_system),
            trend_satisfaction_system.after(trend_spread_system),
            clear_just_consumed_system.after(trend_satisfaction_system),
            crate::layer1::gastronomy::handle_work_speed_buff_decay.after(decay_needs_system),
            crate::layer1::gastronomy::handle_hallucination_decay.after(decay_needs_system),
        )
            .in_set(Layer1SystemSet::Consumption),
    );

    schedule.add_systems(
        (
            crate::layer1::justice::update_inmates_system.after(decay_needs_system),
            crate::layer1::day_night::circadian_rhythm_system.after(consume_food_system),
            aging_system.after(consume_food_system),
            natural_death_system.after(aging_system),
            memory_decay_system.after(decay_needs_system),
            notification_expiration_system.after(decay_needs_system),
            crate::layer1::temperature::thermal_damage_system.after(decay_needs_system),
            crate::layer1::radioactive::sickness_damage_system.after(decay_needs_system),
            pressure_damage_system.after(decay_needs_system),
            crate::layer1::needs::starvation_damage_system.after(decay_needs_system),
            crate::layer1::atmosphere::apply_smog_damage_system.after(decay_needs_system),
            crate::layer1::health::check_health_status_system
                .after(crate::layer1::needs::starvation_damage_system)
                .after(crate::layer1::atmosphere::apply_smog_damage_system)
                .after(crate::layer1::temperature::thermal_damage_system)
                .after(crate::layer1::radioactive::sickness_damage_system)
                .after(pressure_damage_system)
                .after(natural_death_system),
        )
            .in_set(Layer1SystemSet::Consumption),
    );

    schedule.add_systems(
        (
            crate::layer1::pop::handle_pop_death_system
                .after(crate::layer1::health::check_health_status_system),
            crate::layer1::fauna::handle_fauna_death_system
                .after(crate::layer1::health::check_health_status_system),
            crate::layer1::pop::handle_witness_death_system
                .after(crate::layer1::pop::handle_pop_death_system),
            mascot_death_grief_system.after(crate::layer1::health::check_health_status_system),
            crate::layer1::ecology::handle_keystone_death
                .after(crate::layer1::health::check_health_status_system)
                .before(crate::layer1::health::despawn_dead_entities_system),
            crate::layer1::kinetic_storage::handle_battery_destruction_system
                .after(crate::layer1::health::check_health_status_system)
                .before(crate::layer1::health::despawn_dead_entities_system),
            #[cfg(feature = "nova")]
            crate::layer1::loci::record_death_loci_system
                .after(crate::layer1::pop::handle_pop_death_system)
                .before(crate::layer1::health::despawn_dead_entities_system),
            crate::layer1::health::despawn_dead_entities_system
                .after(crate::layer1::pop::handle_pop_death_system)
                .after(crate::layer1::fauna::handle_fauna_death_system)
                .after(mascot_death_grief_system)
                .after(crate::layer1::ecology::handle_keystone_death),
            clean_dead_residents_system.after(crate::layer1::health::despawn_dead_entities_system),
            clean_dead_workers_system.after(crate::layer1::health::despawn_dead_entities_system),
        )
            .in_set(Layer1SystemSet::Consumption),
    );
}
