use super::Layer1SystemSet;
use crate::layer1::direct_link::{apply_buffs, handle_direct_movement, handle_possession};
use crate::layer1::*;
use bevy_ecs::prelude::*;

pub fn register(schedule: &mut Schedule) {
    schedule.add_systems(
        crate::layer1::social::zero_g_sports::zero_g_sports_system
            .in_set(super::Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        (
            crate::layer1::zone::apply_zone_designation_system,
            crate::layer1::digital_immortality::handle_mind_upload,
            crate::layer1::digital_immortality::process_ghost_hacks,
            crate::layer1::construction::process_great_work_phases,
            crate::layer1::room_quality::apply_waking_thoughts_system
                .after(crate::layer1::zone::apply_zone_designation_system),
            assign_sleepwalk_target_system
                .after(crate::layer1::room_quality::apply_waking_thoughts_system),
            cleanup_previous_assignment_system.after(assign_sleepwalk_target_system),
            crate::layer1::customs::immigration_interception_system
                .after(cleanup_previous_assignment_system),
            crate::layer1::tech::rhythm::update_rhythm_system
                .after(cleanup_previous_assignment_system),
            handle_possession.before(process_start_plan_system),
            apply_buffs.after(handle_possession),
            crate::layer1::artifacts::vr_pod::update_vr_pods_system
                .after(cleanup_previous_assignment_system),
            crate::layer1::artifacts::vr_pod::cleanup_vr_pod_status_system
                .after(crate::layer1::artifacts::vr_pod::update_vr_pods_system),
            process_start_plan_system
                .after(crate::layer1::customs::immigration_interception_system),
            crate::layer1::integration::drone_spawner_bridge_system
                .after(process_start_plan_system),
            crate::layer1::integration::drone_work_bridge_system.after(process_start_plan_system),
            crate::layer1::husbandry::pasture_confinement_system.after(process_start_plan_system),
            crate::layer1::fauna::fauna_behavior_system.after(process_start_plan_system),
            mascot_behavior_system.after(process_start_plan_system),
            crate::layer1::the_visitor::the_visitor_behavior_system
                .after(process_start_plan_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::day_night::update_day_night_cycle_system
                .after(process_start_plan_system),
            crate::layer1::day_night::update_ambient_light_from_cycle_system
                .after(crate::layer1::day_night::update_day_night_cycle_system),
            update_bioluminescence_system
                .after(crate::layer1::day_night::update_day_night_cycle_system),
            crate::layer1::pop::reset_speed_system.before(apply_lighting_penalties_system),
            crate::layer1::tech::event_horizon_tap::apply_time_dilation_system
                .after(crate::layer1::pop::reset_speed_system)
                .before(apply_lighting_penalties_system),
            crate::layer1::tech::apply_cognitive_overclocking_system
                .after(crate::layer1::pop::reset_speed_system)
                .before(apply_lighting_penalties_system),
            crate::layer1::tech::process_neural_burnout_system,
            crate::layer1::tech::check_burnout_threshold_system,
            crate::layer1::tech::machine_awakening::process_bot_sentience,
            crate::layer1::tech::machine_awakening::apply_awakened_needs,
            update_lighting_system
                .after(process_start_plan_system)
                .after(crate::layer1::day_night::update_ambient_light_from_cycle_system)
                .after(update_bioluminescence_system),
            crate::layer1::environment::light_pollution::calculate_sky_glow_system
                .after(update_lighting_system),
            crate::layer1::environment::light_pollution::apply_light_pollution_system
                .after(crate::layer1::environment::light_pollution::calculate_sky_glow_system),
            crate::layer1::integration::nocturnal_aggression_bridge_system
                .after(crate::layer1::environment::light_pollution::apply_light_pollution_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            apply_lighting_penalties_system.after(update_lighting_system),
            crate::layer1::environment::ignition::process_ignition
                .after(crate::layer1::combat::hit_stop_system),
            apply_weather_effects_system.after(apply_lighting_penalties_system),
            crate::layer1::nature::mutagenic_rain::apply_mutagenic_rain_system
                .after(apply_weather_effects_system),
            crate::layer1::nature::mutagenic_rain::clear_mutation_immunity_system
                .after(crate::layer1::nature::mutagenic_rain::apply_mutagenic_rain_system),
            apply_quirk_modifiers_system
                .after(apply_lighting_penalties_system)
                .after(apply_weather_effects_system),
            crate::layer1::chemical::apply_chemical_speed_modifiers_system,
            crate::layer1::cryo_shock::apply_cryo_debuff_system
                .after(crate::layer1::pop::reset_speed_system)
                .before(crate::layer1::chemical::apply_chemical_speed_modifiers_system)
                .after(apply_quirk_modifiers_system),
            #[cfg(feature = "nova")]
            crate::layer1::observer::observer_reaction_system
                .after(apply_lighting_penalties_system),
            #[cfg(feature = "nova")]
            crate::layer1::machine_consciousness::consciousness_effect_system
                .after(crate::layer1::pop::reset_speed_system),
            crate::layer1::combat::hit_stop_system.after(process_start_plan_system),
            crate::layer1::sonic_suppression::sonic_suppression_system,
            crate::layer1::combat::combat_cooldown_system.after(process_start_plan_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::logistics::glider::update_glider_movement_system
                .after(crate::layer1::pop::reset_speed_system),
            crate::layer1::logistics::mass_driver::mass_driver_launch_system,
            crate::layer1::logistics::mass_driver::package_arrival_system,
            crate::layer1::logistics::commute::process_orbital_commutes
                .after(process_start_plan_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            movement_system
                .after(apply_quirk_modifiers_system)
                .after(crate::layer1::fauna::fauna_behavior_system)
                .after(crate::layer1::combat::hit_stop_system),
            crate::layer1::infrastructure::transit_toll_system.after(movement_system),
            handle_direct_movement.after(crate::layer1::combat::hit_stop_system),
            crate::layer1::crowding::crowding_accumulation_system.after(movement_system),
            crate::layer1::artifacts::apply_artifact_auras_system.after(movement_system),
            arrival_handler_system.after(movement_system),
            work_execution_system.after(arrival_handler_system),
            crate::layer1::customs::vetting_work_system.after(arrival_handler_system),
            crate::layer1::hobby::execute_hobby_system.after(arrival_handler_system),
            crate::layer1::husbandry::tame_execution_system.after(arrival_handler_system),
            combat_execution_system.after(arrival_handler_system),
            crate::layer1::turret::turret_fire_system.after(combat_execution_system),
            crate::layer1::law::justice::warden_execution_system.after(combat_execution_system),
            crate::layer1::law::predictive_policing::pre_crime_execution_system
                .after(combat_execution_system),
            crate::layer1::hygiene::shower_use_system.after(work_execution_system),
            crate::layer1::hum::execute_listen_to_hum_system.after(arrival_handler_system),
            crate::layer1::clutter::clutter_cleaning_system.after(arrival_handler_system),
            crate::layer1::tech::ghost_code::purge_execution_system.after(arrival_handler_system),
            crate::layer1::tech::martyrs_engine::attune_engine_system.after(arrival_handler_system),
            crate::layer1::tech::harmonic::process_harmonic_mining.after(arrival_handler_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::tinkering::obsessive_optimization_system,
            crate::layer1::execution::vandalize_execution_system.after(arrival_handler_system),
            crate::layer1::pop_doppelganger::sabotage_system.after(work_execution_system),
            crate::layer1::drone::check_drone_connection.after(arrival_handler_system),
            crate::layer1::drone::process_feral_drones
                .after(crate::layer1::drone::check_drone_connection),
            crate::layer1::drone::process_charge_system.after(arrival_handler_system),
            update_social_class_system.after(arrival_handler_system),
            class_friction_system.after(update_social_class_system),
            haul_system.after(arrival_handler_system),
            conveyor_system.after(haul_system),
            crate::layer1::logistics::pneumatic::tube_network_system.after(haul_system),
            crate::layer1::logistics::pneumatic::tube_transport_system
                .after(crate::layer1::logistics::pneumatic::tube_network_system),
            crate::layer1::nanite_fabrication::nanite_fabrication_system
                .after(arrival_handler_system),
            crate::layer1::nanite_fabrication::grey_goo_replication_system
                .after(crate::layer1::nanite_fabrication::nanite_fabrication_system),
            crate::layer1::integration::nanite_breach_chronicle_bridge
                .after(crate::layer1::nanite_fabrication::nanite_fabrication_system),
            process_scan_system.after(arrival_handler_system),
            update_cabin_fever_system.after(movement_system),
            crate::layer1::social::empty_room::visit_sanctuary_system.after(movement_system),
            crate::layer1::tech::hypno_learning::hypno_sleep_system.after(arrival_handler_system),
            crate::layer1::tech::hypno_learning::wake_up_hypno_system
                .after(process_start_plan_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::entities::swarm_intelligence::update_drone_clusters,
            crate::layer1::entities::swarm_intelligence::update_drone_behavior
                .after(crate::layer1::entities::swarm_intelligence::update_drone_clusters),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::flora::consume_silent_flora_system.after(movement_system),
            crate::layer1::fauna::suppress_fauna_system.after(movement_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::agony_extract::process_agony_extract_harvest_system
                .after(work_execution_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );
    schedule.add_systems(
        (crate::layer1::tech::hypno_learning::update_mental_fog_system.after(movement_system),)
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            wild_child_system.after(movement_system),
            update_erosion_system.after(movement_system),
            crate::layer1::particles::particle_physics_system.after(movement_system),
            crate::layer1::particles::particle_system
                .after(crate::layer1::particles::particle_physics_system),
            infiltration_system.after(movement_system),
            discovery_system.after(process_scan_system),
        )
            .in_set(Layer1SystemSet::Execution),
    );

    schedule.add_systems(
        (
            crate::layer1::shipbreaking::spawn_crashed_ship_system.after(process_start_plan_system),
            crate::layer1::shipbreaking::mine_system.after(arrival_handler_system),
            crate::layer1::shipbreaking::hull_destroyed_system
                .after(crate::layer1::shipbreaking::mine_system),
            crate::layer1::grafting::process_grafting,
            crate::layer1::administration::edicts::handle_policy_toggle_system,
            crate::layer1::administration::edicts::handle_hack_hub_system,
            crate::layer1::law::orphaned_edict::orphaned_edict_enforcement_system,
            crate::layer1::law::aesthetic_edict::enforce_aesthetic_edict_system,
        )
            .in_set(Layer1SystemSet::Execution),
    );
}
