use scale::layer1::hazards::wakes::{resolve_subspace_wakes_system, Displaced};
use scale::layer2::ftl::wakes::{generate_subspace_wake_system, FtlJumpEvent, SubspaceWakeEvent};
use scale::layer1::map::GridPosition;
use scale::layer1::core::chronicle::AddChronicleEvent;
use bevy::prelude::*;

#[test]
fn test_subspace_stowaways_integration() {
    let mut app = App::new();
    app.add_plugins(MinimalPlugins);

    app.init_resource::<Events<FtlJumpEvent>>();
    app.init_resource::<Events<SubspaceWakeEvent>>();
    app.init_resource::<Events<AddChronicleEvent>>();

    app.add_systems(Update, (
        generate_subspace_wake_system,
        resolve_subspace_wakes_system,
        scale::layer1::core::integration::subspace_stowaways_chronicle_bridge,
    ).chain());

    let target_system = app.world_mut().spawn_empty().id();
    app.world_mut().spawn(GridPosition { x: 10, y: 10 });
    app.world_mut().spawn(GridPosition { x: 20, y: 20 });

    app.world_mut().resource_mut::<Events<FtlJumpEvent>>().send(FtlJumpEvent {
        drive_quality: 0.0,
        target_system,
    });

    app.update();

    let displaced_count = app.world_mut().query::<&Displaced>().iter(app.world()).count();
    assert!(displaced_count > 0, "Entities should have been displaced by the subspace wake");

    let chronicle_events = app.world().resource::<Events<AddChronicleEvent>>();
    let mut reader = chronicle_events.get_cursor();
    let events: Vec<_> = reader.read(chronicle_events).collect();
    assert_eq!(events.len(), 1, "A Chronicle event should be generated by the subspace wake");
    assert!(events[0].text.contains("subspace wake disrupted the colony"));
}
