//! The Architecture of Regret
//!
//! The literal foundations of your empire remember the atrocities committed to build it.
//! If a colony is built on the ruins of a conquered civilization, the new buildings absorb
//! the psychic resonance of the dead. As your empire expands, these resonant buildings
//! start generating a new unique resource: `Guilt`.
//!
//! Guilt can be harnessed to power incredibly strong psychic weapons or shields, but
//! its lingering presence causes massive, continuous unrest among the populace.
//!
//! # Core Mechanics
//!
//! - **[`PsychicResonance`]**: A component attached to buildings constructed over ancient ruins.
//! - **[`GuiltResource`]**: A global resource representing accumulated collective guilt.
//! - **[`process_guilt_generation_system`]**: Aggregates resonance to generate `Guilt`.
//! - **[`apply_guilt_unrest_system`]**: Translates accumulated `Guilt` into tangible `Unrest`.

use crate::layer1::social::unrest::{Unrest, UnrestModifier};
use bevy::prelude::*;

/// A global resource tracking the accumulated psychic guilt of the colony.
///
/// Guilt is generated by buildings with [`PsychicResonance`] and can be spent on
/// powerful psychic technologies, but causes continuous societal unrest if allowed
/// to pool in large quantities.
///
/// # Examples
/// ```
/// use bevy::prelude::*;
/// use scale::layer3::guilt::GuiltResource;
///
/// let mut world = World::new();
/// world.insert_resource(GuiltResource { amount: 50.0 });
///
/// assert_eq!(world.resource::<GuiltResource>().amount, 50.0);
/// ```
#[derive(Resource, Default, Debug)]
pub struct GuiltResource {
    /// The current amount of guilt.
    pub amount: f32,
}

/// A component marking a building that emits psychic guilt.
///
/// This is typically attached to buildings that were constructed directly on top
/// of the ruins of conquered civilizations. The restless spirits of the past
/// seep into the architecture, emitting a continuous resonance.
///
/// # Examples
/// ```
/// use bevy::prelude::*;
/// use scale::layer3::guilt::PsychicResonance;
///
/// let mut world = World::new();
/// let haunted_factory = world.spawn(PsychicResonance { intensity: 10.0 }).id();
///
/// assert_eq!(world.get::<PsychicResonance>(haunted_factory).unwrap().intensity, 10.0);
/// ```
#[derive(Component, Debug)]
pub struct PsychicResonance {
    /// The intensity of guilt generated per tick.
    pub intensity: f32,
}

/// Aggregates all [`PsychicResonance`] in the world and adds it to the [`GuiltResource`].
///
/// This system scans the colony for any resonant architecture and funnels their
/// psychic emanations into the global guilt pool.
///
/// # Examples
/// ```
/// use bevy::prelude::*;
/// use scale::layer3::guilt::{GuiltResource, PsychicResonance, process_guilt_generation_system};
///
/// let mut app = App::new();
/// app.insert_resource(GuiltResource { amount: 0.0 });
///
/// // Spawn a building radiating guilt
/// app.world_mut().spawn(PsychicResonance { intensity: 5.0 });
///
/// app.add_systems(Update, process_guilt_generation_system);
/// app.update();
///
/// // The guilt should be added to the resource pool
/// assert_eq!(app.world().resource::<GuiltResource>().amount, 5.0);
/// ```
pub fn process_guilt_generation_system(
    mut guilt: ResMut<GuiltResource>,
    query: Query<&PsychicResonance>,
) {
    let mut total_resonance = 0.0;
    for resonance in query.iter() {
        total_resonance += resonance.intensity;
    }
    guilt.amount += total_resonance;
}

/// Converts accumulated [`GuiltResource`] into societal [`Unrest`].
///
/// The psychic weight of the colony's sins manifests as tangible nightmares and
/// anxiety among the population, slowly driving the unrest level higher.
///
/// # Panics
/// Panics if the `Unrest` resource has not been initialized in the `World`.
///
/// # Examples
/// ```
/// use bevy::prelude::*;
/// use scale::layer1::social::unrest::Unrest;
/// use scale::layer3::guilt::{GuiltResource, apply_guilt_unrest_system};
///
/// let mut app = App::new();
/// app.insert_resource(GuiltResource { amount: 100.0 });
/// app.insert_resource(Unrest { level: 0.0, modifiers: vec![] });
///
/// app.add_systems(Update, apply_guilt_unrest_system);
/// app.update();
///
/// // 100 Guilt should generate a 10.0 value UnrestModifier
/// let unrest = app.world().resource::<Unrest>();
/// assert_eq!(unrest.modifiers.len(), 1);
/// assert_eq!(unrest.modifiers[0].value, 10.0);
/// assert_eq!(unrest.modifiers[0].label, "Psychic Resonance");
/// ```
pub fn apply_guilt_unrest_system(guilt: Res<GuiltResource>, mut unrest: ResMut<Unrest>) {
    if guilt.amount == 0.0 {
        return;
    }

    let unrest_increase = guilt.amount * 0.1; // 10% conversion to unrest
    let unrest_increase = unrest_increase.min(50.0); // Cap at 50

    // Look for existing modifier to prevent spamming the vector every tick
    let mut found = false;
    for modifier in unrest.modifiers.iter_mut() {
        if modifier.label == "Psychic Resonance" {
            modifier.value = unrest_increase;
            modifier.duration = 10;
            found = true;
        }
    }
    if !found {
        unrest.modifiers.push(UnrestModifier {
            value: unrest_increase,
            duration: 10,
            label: "Psychic Resonance".to_string(),
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layer1::architecture::building::{BuildingType, MaterialType};
    use crate::layer1::architecture::ruins::Ruin;
    use crate::layer1::GridPosition;

    #[test]
    fn test_building_on_ruins_generates_psychic_resonance() {
        let mut world = World::new();
        // Setup ruin
        world.spawn((
            Ruin {
                original_type: BuildingType::Housing,
                material: MaterialType::Stone,
            },
            GridPosition { x: 5, y: 5 },
            PsychicResonance { intensity: 10.0 }, // Emits resonance
        ));

        // When a building is placed on the ruin, it absorbs the resonance
        let _new_building = world
            .spawn((
                crate::layer1::architecture::building::Building {
                    building_type: BuildingType::Smelter,
                },
                GridPosition { x: 5, y: 5 },
            ))
            .id();

        // This is a minimal unit test concept: we verify if the resonance from a ruin
        // influences the building. Real setup would involve the construction system adding PsychicResonance.

        // For the sake of this mock test, we assert that the world contains the entities
        let mut query = world.query::<&PsychicResonance>();
        let mut count = 0;
        for _ in query.iter(&world) {
            count += 1;
        }
        assert_eq!(count, 1, "The ruin should emit psychic resonance.");
    }

    #[test]
    fn test_guilt_resource_generation() {
        let mut app = App::new();
        app.insert_resource(GuiltResource { amount: 0.0 });
        app.add_systems(Update, process_guilt_generation_system);

        // Setup a resonant building
        app.world_mut().spawn((
            crate::layer1::architecture::building::Building {
                building_type: BuildingType::Smelter,
            },
            PsychicResonance { intensity: 5.0 },
        ));

        app.update();

        // Assert guilt generated
        assert_eq!(app.world().resource::<GuiltResource>().amount, 5.0);
    }

    #[test]
    fn test_guilt_causes_unrest() {
        let mut app = App::new();
        app.insert_resource(GuiltResource { amount: 100.0 });
        app.insert_resource(Unrest {
            level: 0.0,
            modifiers: vec![],
        });
        app.add_systems(Update, apply_guilt_unrest_system);

        app.update();

        let unrest = app.world().resource::<Unrest>();
        assert_eq!(unrest.modifiers.len(), 1);
        assert_eq!(unrest.modifiers[0].value, 10.0);
        assert_eq!(unrest.modifiers[0].label, "Psychic Resonance");
    }
}
