//! Digital Immortality and Mainframe Systems
//!
//! This module provides mechanics for uploading Pops into the colony Mainframe, transforming
//! them into Digital Ghosts. This completely removes their biological needs at the cost of
//! significantly increased power draw and the risk of bored Ghosts hacking colony infrastructure.

use crate::layer1::skills::Skills;
use bevy::prelude::*;

/// Digital Ghost component - applied when a pop is uploaded to the mainframe.
#[derive(Component)]
pub struct Ghost;

/// Mainframe component - capable of storing ghost populations.
#[derive(Component)]
pub struct Mainframe {
    /// Maximum capacity of ghost pops.
    pub capacity: u32,
}

/// Boredom level - ghost specific need parameter.
#[derive(Component)]
pub struct Boredom {
    /// The current level of boredom.
    pub level: f32,
}

/// Event triggered to upload a pop's mind into a mainframe.
#[derive(Event)]
pub struct MindUploadEvent {
    /// The target pop entity being uploaded.
    pub target_pop: Entity,
    /// The destination mainframe entity.
    pub destination_mainframe: Entity,
}

/// Event triggered when a ghost hacks into the colony systems out of boredom.
#[derive(Event)]
pub struct GhostHackEvent {
    /// The ghost entity executing the hack.
    pub hacker: Entity,
    /// The target infrastructure entity being hacked.
    pub target: Entity,
}

/// Uploads biological minds into a digital format, removing biological needs and housing them in a mainframe.
///
/// # Examples
/// ```
/// use bevy::prelude::*;
/// use scale::layer1::digital_immortality::*;
/// use scale::layer1::skills::Skills;
/// use scale::layer1::psychology::needs::Needs;
/// use scale::layer1::architecture::housing::Housing;
///
/// let mut app = App::new();
/// app.add_plugins(MinimalPlugins);
/// app.add_event::<MindUploadEvent>();
/// app.add_systems(Update, handle_mind_upload);
///
/// let pop = app.world_mut().spawn((Name::new("Bob"), Skills::default(), Needs::default())).id();
/// let mainframe = app.world_mut().spawn((Mainframe { capacity: 10 }, Housing { capacity: 10, residents: vec![] })).id();
///
/// app.world_mut().resource_mut::<Events<MindUploadEvent>>().send(MindUploadEvent {
///     target_pop: pop,
///     destination_mainframe: mainframe,
/// });
/// app.update();
///
/// assert!(app.world().get::<Ghost>(pop).is_some());
/// assert!(app.world().get::<Needs>(pop).is_none());
/// ```
pub fn handle_mind_upload(
    mut commands: Commands,
    mut events: EventReader<MindUploadEvent>,
    query: Query<(Entity, &Skills, &Name)>,
    mut housing_query: Query<&mut crate::layer1::architecture::housing::Housing, With<Mainframe>>,
) {
    for event in events.read() {
        if let Ok((entity, _skills, _name)) = query.get(event.target_pop) {
            commands
                .entity(entity)
                .remove::<crate::layer1::needs::Needs>()
                // Note: Realistically would also need to remove health components or mark them physically inactive.
                .insert(Ghost)
                .insert(Boredom { level: 0.0 });

            if let Ok(mut housing) = housing_query.get_mut(event.destination_mainframe) {
                if housing.residents.len() < housing.capacity {
                    housing.residents.push(entity);
                }
            }
        }
    }
}

/// Scales the power consumption of a mainframe relative to the number of ghosts it contains.
pub fn ghost_power_consumption(
    mut mainframes: Query<
        (
            &mut crate::layer1::energy::PowerConsumer,
            &crate::layer1::architecture::housing::Housing,
        ),
        With<Mainframe>,
    >,
) {
    for (mut receiver, housing) in mainframes.iter_mut() {
        let ghost_count = housing.residents.len() as u32;
        receiver.demand = 500.0 + (ghost_count as f32 * 200.0);
    }
}

/// Processes hacking actions generated by bored ghosts, such as toggling access control logic.
pub fn process_ghost_hacks(
    mut events: EventReader<GhostHackEvent>,
    mut doors: Query<&mut crate::layer1::access_control::AccessControl>,
) {
    for event in events.read() {
        if let Ok(mut door) = doors.get_mut(event.target) {
            // Toggles the lock status for fun
            if door.mode == crate::layer1::access_control::AccessMode::Lockdown {
                door.mode = crate::layer1::access_control::AccessMode::Public;
            } else {
                door.mode = crate::layer1::access_control::AccessMode::Lockdown;
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layer1::access_control::{AccessControl, AccessMode};
    use crate::layer1::architecture::housing::Housing;
    use crate::layer1::energy::PowerConsumer;
    use crate::layer1::entities::pop::Pop;
    use crate::layer1::needs::Needs;
    use crate::layer1::skills::SkillType;
    use std::collections::HashMap;

    #[test]
    fn test_mind_upload_transfer() {
        let mut app = App::new();
        app.add_plugins(MinimalPlugins);

        app.add_event::<MindUploadEvent>();
        app.add_systems(Update, handle_mind_upload);

        let mut xp = HashMap::new();
        xp.insert(SkillType::Crafting, 95.0);

        let engineer_entity = app
            .world_mut()
            .spawn((
                Pop,
                Name::new("Master Vance"),
                Skills { xp },
                Needs {
                    hunger: 50.0,
                    rest: 20.0,
                    ..Default::default()
                },
            ))
            .id();

        let mainframe = app
            .world_mut()
            .spawn((
                Mainframe { capacity: 10 },
                Housing {
                    capacity: 10,
                    residents: Vec::new(),
                },
                PowerConsumer {
                    demand: 500.0,
                    ..Default::default()
                },
            ))
            .id();

        app.world_mut()
            .resource_mut::<Events<MindUploadEvent>>()
            .send(MindUploadEvent {
                target_pop: engineer_entity,
                destination_mainframe: mainframe,
            });
        app.update();

        assert!(
            app.world().get::<Ghost>(engineer_entity).is_some(),
            "Pop should become a Ghost"
        );
        assert!(
            app.world().get::<Needs>(engineer_entity).is_none(),
            "Ghosts have no biological needs"
        );
        let skills = app.world().get::<Skills>(engineer_entity).unwrap();
        assert_eq!(
            *skills.xp.get(&SkillType::Crafting).unwrap(),
            95.0,
            "Skills should be preserved after upload"
        );

        let housing = app.world().get::<Housing>(mainframe).unwrap();
        assert!(
            housing.residents.contains(&engineer_entity),
            "Ghost should be resident of mainframe"
        );
    }

    #[test]
    fn test_ghost_power_drain() {
        let mut app = App::new();
        app.add_plugins(MinimalPlugins);
        app.add_systems(Update, ghost_power_consumption);

        let ghost_entity = app.world_mut().spawn(Ghost).id();

        let mainframe = app
            .world_mut()
            .spawn((
                Mainframe { capacity: 10 },
                Housing {
                    capacity: 10,
                    residents: vec![ghost_entity],
                },
                PowerConsumer {
                    demand: 500.0,
                    ..Default::default()
                },
            ))
            .id();

        app.update();

        let receiver = app.world().get::<PowerConsumer>(mainframe).unwrap();
        assert!(
            receiver.demand > 500.0,
            "Ghosts should massively increase power drain"
        );
        assert_eq!(receiver.demand, 700.0, "1 Ghost = +200 drain");
    }

    #[test]
    fn test_ghost_insanity_hack() {
        let mut app = App::new();
        app.add_plugins(MinimalPlugins);
        app.add_event::<GhostHackEvent>();
        app.add_systems(Update, process_ghost_hacks);

        let door_entity = app
            .world_mut()
            .spawn(AccessControl {
                mode: AccessMode::Public,
                ..Default::default()
            })
            .id();
        let ghost = app
            .world_mut()
            .spawn((Ghost, Boredom { level: 100.0 }))
            .id();

        app.world_mut()
            .resource_mut::<Events<GhostHackEvent>>()
            .send(GhostHackEvent {
                hacker: ghost,
                target: door_entity,
            });
        app.update();

        let door = app.world().get::<AccessControl>(door_entity).unwrap();
        assert_eq!(
            door.mode,
            AccessMode::Lockdown,
            "Ghost should hack and lock the door"
        );
    }
}
