use bevy::prelude::*;

use crate::layer1::utility_types::AssignmentType as JobType;
use crate::layer1::pop::{Pop, Job};
use crate::layer1::unrest::Unrest;

// --- Components and Resources ---

/// Placed on buildings where secrets can be sold to outside factions.
#[derive(Component)]
pub struct Broker;

/// Represents a secret currency.
#[derive(Component)]
pub struct Secret;

/// Global count of secrets gathered by the colony.
#[derive(Resource, Default)]
pub struct ColonySecrets {
    pub count: u32,
}

/// Global tracking of colony paranoia, generated by trading secrets.
#[derive(Resource, Default)]
pub struct GlobalParanoia {
    pub level: f32,
}

/// Event fired to trade secrets using a broker.
#[derive(Event)]
pub struct TradeSecretEvent {
    pub broker_entity: Entity,
    pub secret_value: u32,
}

// --- Systems ---

/// Generates secrets randomly from pops working in certain jobs.
pub fn generate_secrets_system(
    mut secrets: ResMut<ColonySecrets>,
    query: Query<&Job, With<Pop>>,
) {
    // In tests, we might want deterministic behavior.
    // For normal gameplay, we rely on a pseudo-random chance per tick.
    // Using `gen_bool` with a small chance simulates discovering a secret over time.
    let mut rng = rand::thread_rng();
    for job in query.iter() {
        if job.job_type == JobType::TavernVisitor || job.job_type == JobType::ObservatoryWorker {
            if rand::Rng::gen_bool(&mut rng, 0.01) { // 1% chance per tick
                secrets.count += 1;
            }
        }
    }
}

/// Auto-sells secrets when a broker is present and we have enough secrets.
pub fn broker_auto_trade_system(
    mut events: EventWriter<TradeSecretEvent>,
    secrets: Res<ColonySecrets>,
    query: Query<Entity, With<Broker>>,
) {
    // Arbitrary threshold to trigger a sale
    if secrets.count >= 5 {
        if let Some(broker_entity) = query.iter().next() {
            events.send(TradeSecretEvent {
                broker_entity,
                secret_value: 5,
            });
        }
    }
}

/// Executes a whisper trade, consuming secrets and increasing global paranoia.
pub fn execute_whisper_trade_system(
    mut events: EventReader<TradeSecretEvent>,
    mut secrets: ResMut<ColonySecrets>,
    mut paranoia: ResMut<GlobalParanoia>,
) {
    for event in events.read() {
        if secrets.count >= event.secret_value {
            secrets.count -= event.secret_value;
            paranoia.level += 5.0 * (event.secret_value as f32);
        }
    }
}

/// High paranoia causes an increase in global unrest.
pub fn paranoia_unrest_system(
    paranoia: Res<GlobalParanoia>,
    mut unrest: ResMut<Unrest>,
) {
    if paranoia.level > 50.0 {
        let unrest_increase = (paranoia.level - 50.0) * 0.01;
        unrest.level = (unrest.level + unrest_increase).clamp(0.0, 1.0);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_secret_generation_in_tavern() {
        let mut app = App::new();
        app.insert_resource(ColonySecrets::default());
        app.add_systems(Update, generate_secrets_system);

        // Instead of true RNG relying on 1000 ticks, we just add many pops to guarantee generation
        // statistically (99.999% chance over 1000 pops).
        for _ in 0..1000 {
            app.world_mut().spawn((
                Pop,
                Job { job_type: JobType::TavernVisitor, workplace: Entity::PLACEHOLDER },
            ));
        }

        app.update();

        let has_secret = app.world().get_resource::<ColonySecrets>().map_or(0, |res| res.count) > 0;
        assert!(has_secret, "A secret should have been generated.");
    }

    #[test]
    fn test_broker_trade_increases_paranoia() {
        let mut app = App::new();
        app.insert_resource(ColonySecrets { count: 1 });
        app.insert_resource(GlobalParanoia { level: 0.0 });
        app.add_event::<TradeSecretEvent>();
        app.add_systems(Update, execute_whisper_trade_system);

        let broker = app.world_mut().spawn(Broker).id();

        app.world_mut().send_event(TradeSecretEvent {
            broker_entity: broker,
            secret_value: 1
        });
        app.update();

        assert_eq!(app.world().resource::<ColonySecrets>().count, 0);
        assert!(app.world().resource::<GlobalParanoia>().level > 0.0);
    }

    #[test]
    fn test_high_paranoia_causes_unrest() {
        let mut app = App::new();
        app.insert_resource(GlobalParanoia { level: 90.0 });
        app.insert_resource(Unrest { level: 0.0, ..Default::default() });
        app.add_systems(Update, paranoia_unrest_system);

        app.update();

        let unrest = app.world().resource::<Unrest>().level;
        assert!(unrest > 0.0);
    }
}
