use bevy_ecs::prelude::*;

#[derive(Component)]
pub struct Faction {
    pub name: String,
}

impl Faction {
    pub fn new(name: &str) -> Self {
        Self {
            name: name.to_string(),
        }
    }
}

#[derive(Component)]
pub struct AutomatedDiplomat;

#[derive(Event)]
pub struct GenerateDiplomaticInteractionEvent {
    pub faction: Entity,
}

#[derive(Event)]
pub struct DiplomaticInteraction {
    pub faction: Entity,
    pub message: String,
}

pub fn generate_diplomatic_interaction_system(
    mut trigger_events: EventReader<GenerateDiplomaticInteractionEvent>,
    mut interaction_events: EventWriter<DiplomaticInteraction>,
    query: Query<&Faction, With<AutomatedDiplomat>>,
) {
    for event in trigger_events.read() {
        if let Ok(faction) = query.get(event.faction) {
            interaction_events.send(DiplomaticInteraction {
                faction: event.faction,
                message: format!("Automated script from {} running on loop.", faction.name),
            });
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use bevy_app::prelude::*;

    struct DiplomacyPlugin;

    impl Plugin for DiplomacyPlugin {
        fn build(&self, app: &mut App) {
            app.add_event::<GenerateDiplomaticInteractionEvent>()
                .add_event::<DiplomaticInteraction>()
                .add_systems(Update, generate_diplomatic_interaction_system);
        }
    }

    #[test]
    fn test_automated_script_trade_deal() {
        let mut app = App::new();
        app.add_plugins(DiplomacyPlugin);

        // Arrange: Spawn an automated faction
        let faction = app
            .world_mut()
            .spawn((Faction::new("ScriptBot"), AutomatedDiplomat))
            .id();

        // Act: Trigger the diplomacy generation tick
        app.world_mut().send_event(GenerateDiplomaticInteractionEvent { faction });
        app.update();

        // Assert deal is generated by automated script, perhaps having a specific marker
        let interactions = app.world().resource::<Events<DiplomaticInteraction>>();
        assert!(!interactions.is_empty());
    }
}
