use bevy::prelude::*;

#[derive(Component)]
pub struct AutomatedDiplomat;

#[derive(Event, Debug, Clone)]
pub struct DiplomaticInteraction;

#[derive(Event, Debug, Clone)]
pub struct GenerateDiplomaticInteractionEvent {
    pub faction: Entity,
}

pub fn automated_diplomat_system(
    mut trigger_events: EventReader<GenerateDiplomaticInteractionEvent>,
    automated_query: Query<&AutomatedDiplomat>, // We just check if entity has AutomatedDiplomat component
    mut interaction_events: EventWriter<DiplomaticInteraction>,
) {
    for event in trigger_events.read() {
        if automated_query.contains(event.faction) {
            interaction_events.send(DiplomaticInteraction);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layer3::diplomacy::succession::Faction;

    #[test]
    fn test_automated_script_trade_deal() {
        let mut app = App::new();
        // Register events and systems
        app.add_event::<DiplomaticInteraction>();
        app.add_event::<GenerateDiplomaticInteractionEvent>();
        app.add_systems(Update, automated_diplomat_system);

        // Arrange: Spawn an automated faction
        let faction = app
            .world_mut()
            .spawn((
                Faction {
                    name: "ScriptBot".to_string(),
                },
                AutomatedDiplomat,
            ))
            .id();

        // Act: Trigger the diplomacy generation tick
        app.world_mut()
            .send_event(GenerateDiplomaticInteractionEvent { faction });
        app.update();

        // Assert deal is generated by automated script
        let interactions = app.world().resource::<Events<DiplomaticInteraction>>();
        assert!(!interactions.is_empty());
    }
}
