use bevy::prelude::*;

/// A faction that is actually an automated script.
#[derive(Component)]
pub struct AutomatedDiplomat;

/// Event triggered to generate an interaction.
#[derive(Event)]
pub struct GenerateDiplomaticInteractionEvent {
    /// The faction entity generating the event.
    pub faction: Entity,
}

/// The resulting diplomatic interaction event.
#[derive(Event)]
pub struct DiplomaticInteraction;

/// System to generate diplomatic interactions for automated diplomats.
pub fn generate_diplomatic_interactions_system(
    mut events: EventReader<GenerateDiplomaticInteractionEvent>,
    mut interactions: EventWriter<DiplomaticInteraction>,
    automated_query: Query<&AutomatedDiplomat>,
) {
    for event in events.read() {
        if automated_query.contains(event.faction) {
            interactions.send(DiplomaticInteraction);
        }
    }
}

/// Plugin containing the systems and events for the dead internet feature.
pub struct DeadInternetPlugin;

impl Plugin for DeadInternetPlugin {
    fn build(&self, app: &mut App) {
        app.add_event::<GenerateDiplomaticInteractionEvent>()
           .add_event::<DiplomaticInteraction>()
           .add_systems(Update, generate_diplomatic_interactions_system);
    }
}

#[cfg(test)]
mod tests {
    use crate::layer3::diplomacy::succession::Faction;
    use super::*;

    #[test]
    fn test_automated_script_trade_deal() {
        let mut app = App::new();
        app.add_plugins(DeadInternetPlugin);

        // Arrange: Spawn an automated faction
        let faction = app.world_mut().spawn((Faction { name: "ScriptBot".to_string() }, AutomatedDiplomat)).id();

        // Act: Trigger the diplomacy generation tick
        app.world_mut().send_event(GenerateDiplomaticInteractionEvent { faction });
        app.update();

        // Assert deal is generated by automated script, perhaps having a specific marker
        let interactions = app.world().resource::<Events<DiplomaticInteraction>>();
        assert!(!interactions.is_empty());
    }
}
