#![allow(clippy::type_complexity)]
//! The Bureaucratic Singularity (Nova Feature).
//!
//! # The Spark
//! We have `AdminStats`, `ColonyPolicies`, and `Morale`.
//!
//! # The Feature
//! A system that monitors `AdminStats::efficiency`. When efficiency is perfect (1.0) and supply vastly exceeds demand (e.g. `supply > demand * 2.0`), the bureaucracy "runs out of real problems." To justify its budget, it invents a new useless regulation, spawning an `ObscureRegulation` entity that acts as an `AdminConsumer` (massive demand sink) and applies a temporary negative `MoodModifier` ("Bureaucratic Whiplash") to all Pops.
//! It punishes over-optimization in a very Grimdark/Dilbert way. You want just enough bureaucracy, but too much creates a self-sustaining nightmare.

use crate::layer1::admin::{AdminConsumer, AdminStats};
use crate::layer1::core::chronicle::{AddChronicleEvent, EventImportance};
use crate::layer1::pop::Pop;
use crate::layer1::social::morale::{MoodModifier, Morale};
use bevy_ecs::prelude::*;

/// Component marking an obscure regulation generated by the bureaucratic singularity.
#[derive(Component)]
pub struct ObscureRegulation;

/// System that monitors administration stats and triggers a singularity if over-optimized.
pub fn paperwork_singularity_system(
    mut commands: Commands,
    stats: Option<Res<AdminStats>>,
    mut pop_query: Query<&mut Morale, With<Pop>>,
    mut chronicle_events: EventWriter<AddChronicleEvent>,
) {
    if let Some(stats) = stats {
        // Trigger if:
        // 1. Efficiency is perfect (>= 1.0)
        // 2. We have a significant baseline of demand (e.g., > 10.0) to avoid early-game weirdness
        // 3. Supply is more than double the demand
        if stats.efficiency >= 1.0 && stats.demand > 10.0 && stats.supply > stats.demand * 2.0 {
            // Spawn the regulation that eats admin points
            let demand_sink = stats.supply * 0.5;

            commands.spawn((
                ObscureRegulation,
                AdminConsumer {
                    demand: demand_sink,
                },
            ));

            // Apply Bureaucratic Whiplash to everyone
            let mut applied = false;
            for mut morale in &mut pop_query {
                // Ensure we don't spam the modifier every tick while stats are catching up
                if !morale
                    .modifiers
                    .iter()
                    .any(|m| m.label == "Bureaucratic Whiplash")
                {
                    morale.add_modifier(MoodModifier {
                        label: "Bureaucratic Whiplash".to_string(),
                        value: -0.15,
                        duration: 50,
                    });
                    applied = true;
                }
            }

            // Log it only if we applied the whiplash to prevent log spam
            if applied {
                chronicle_events.send(AddChronicleEvent {
                    text: "The administration, having achieved perfect efficiency, paradoxically invented a convoluted set of obscure regulations to justify its own budget. The colony groans under the weight of new paperwork.".to_string(),
                    importance: EventImportance::Major,
                });
            }
        }
    }
}

pub fn register(schedule: &mut Schedule) {
    schedule.add_systems(paperwork_singularity_system);
}

#[cfg(test)]
mod tests {
    use super::*;
    use bevy_ecs::system::RunSystemOnce;

    #[test]
    fn test_singularity_triggers() {
        let mut world = World::new();
        world.init_resource::<Events<AddChronicleEvent>>();

        // Setup stats to trigger singularity
        world.insert_resource(AdminStats {
            supply: 100.0,
            demand: 20.0,
            efficiency: 1.0,
        });

        // Add a Pop
        let pop = world.spawn((Pop, Morale::default())).id();

        world.run_system_once(paperwork_singularity_system).unwrap();

        // Check if ObscureRegulation spawned
        let reg_count = world.query::<&ObscureRegulation>().iter(&world).count();
        assert_eq!(reg_count, 1, "Should spawn one obscure regulation");

        // Check if AdminConsumer was attached
        let consumer = world.query::<&AdminConsumer>().iter(&world).next().unwrap();
        assert_eq!(consumer.demand, 50.0, "Should sink 50% of supply");

        // Check if Pop got whiplash
        let morale = world.get::<Morale>(pop).unwrap();
        let modifier = morale
            .modifiers
            .iter()
            .find(|m| m.label == "Bureaucratic Whiplash");
        assert!(modifier.is_some(), "Pop should get whiplash modifier");

        // Check chronicle
        let events = world.resource::<Events<AddChronicleEvent>>();
        assert_eq!(events.len(), 1, "Should emit chronicle event");
    }

    #[test]
    fn test_singularity_does_not_trigger_early_game() {
        let mut world = World::new();
        world.init_resource::<Events<AddChronicleEvent>>();

        // Demand < 10.0
        world.insert_resource(AdminStats {
            supply: 10.0,
            demand: 2.0,
            efficiency: 1.0,
        });

        world.run_system_once(paperwork_singularity_system).unwrap();

        let reg_count = world.query::<&ObscureRegulation>().iter(&world).count();
        assert_eq!(reg_count, 0, "Should not spawn regulation in early game");
    }

    #[test]
    fn test_singularity_does_not_trigger_if_not_overoptimized() {
        let mut world = World::new();
        world.init_resource::<Events<AddChronicleEvent>>();

        world.insert_resource(AdminStats {
            supply: 30.0,
            demand: 20.0, // Supply is < Demand * 2.0
            efficiency: 1.0,
        });

        world.run_system_once(paperwork_singularity_system).unwrap();

        let reg_count = world.query::<&ObscureRegulation>().iter(&world).count();
        assert_eq!(reg_count, 0, "Should not spawn regulation");
    }
}
