//! The Somnolent Engine (Nova Feature).
//!
//! # The Spark
//! We have `Dream` and `ColonyResources::fuel` mechanics. What if we monetized the abstract concept of sleep?
//!
//! # The Feature
//! A `DreamDynamo` building component. When Pops sleep near it, it harvests their `rest` need (making them wake up tired)
//! but generates `ColonyResources::fuel`. It represents a sinister industrial optimization where the colony's energy grid
//! is partially powered by the restless subconscious of its inhabitants.

use crate::layer1::map::GridPosition;
use crate::layer1::needs::Needs;
use crate::layer1::pop::Pop;
use crate::layer1::resources::ColonyResources;
use crate::layer1::utility_types::{ActionType, PopAction};
use bevy_ecs::prelude::*;

/// A building component that harvests the sleep energy of nearby Pops to generate fuel.
#[derive(Component, Debug, Clone, Default)]
pub struct DreamDynamo;

const DYNAMO_RANGE: u32 = 3;
const REST_DRAIN_PER_TICK: f32 = 0.005;
const FUEL_GENERATED_PER_TICK: f32 = 0.1;

/// System that drains rest from sleeping Pops near DreamDynamos and generates fuel.
pub fn somnolent_engine_system(
    mut resources: ResMut<ColonyResources>,
    dynamos: Query<&GridPosition, With<DreamDynamo>>,
    mut sleeping_pops: Query<(&GridPosition, &mut Needs, &PopAction), With<Pop>>,
) {
    if dynamos.is_empty() {
        return;
    }

    for (pop_pos, mut needs, action) in &mut sleeping_pops {
        // Only target Pops that are currently sleeping
        if action.current != ActionType::SatisfyRest {
            continue;
        }

        // Check if there is any dynamo in range
        let mut near_dynamo = false;
        for dynamo_pos in &dynamos {
            if pop_pos.distance_chebyshev(*dynamo_pos) <= DYNAMO_RANGE {
                near_dynamo = true;
                break;
            }
        }

        if near_dynamo {
            // Drain rest (cannot go below 0.0)
            if needs.rest > 0.0 {
                needs.rest = (needs.rest - REST_DRAIN_PER_TICK).max(0.0);

                // Generate fuel (cannot exceed max_fuel)
                resources.fuel = (resources.fuel + FUEL_GENERATED_PER_TICK).min(resources.max_fuel);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use bevy_ecs::system::RunSystemOnce;

    #[test]
    fn test_somnolent_engine_drains_rest_and_generates_fuel() {
        let mut world = World::new();

        world.insert_resource(ColonyResources {
            fuel: 0.0,
            max_fuel: 100.0,
            ..Default::default()
        });

        // Spawn a DreamDynamo
        world.spawn((DreamDynamo, GridPosition { x: 5, y: 5 }));

        // Spawn a sleeping Pop near the Dynamo
        let pop = world
            .spawn((
                Pop,
                GridPosition { x: 6, y: 6 }, // Within Chebyshev distance 3
                Needs {
                    rest: 1.0,
                    ..Default::default()
                },
                PopAction {
                    current: ActionType::SatisfyRest,
                    ..Default::default()
                },
            ))
            .id();

        // Run the system once
        world.run_system_once(somnolent_engine_system).unwrap();

        // Check if rest was drained and fuel was generated
        let needs = world.get::<Needs>(pop).unwrap();
        let resources = world.resource::<ColonyResources>();

        assert!(
            (needs.rest - (1.0 - REST_DRAIN_PER_TICK)).abs() < f32::EPSILON,
            "Pop rest should be drained by DYNAMO_REST_DRAIN"
        );
        assert!(
            (resources.fuel - FUEL_GENERATED_PER_TICK).abs() < f32::EPSILON,
            "Fuel should be generated by DYNAMO_FUEL_GEN"
        );
    }

    #[test]
    fn test_somnolent_engine_ignores_awake_pops() {
        let mut world = World::new();

        world.insert_resource(ColonyResources {
            fuel: 0.0,
            max_fuel: 100.0,
            ..Default::default()
        });

        world.spawn((DreamDynamo, GridPosition { x: 5, y: 5 }));

        // Pop is near but working, not sleeping
        let pop = world
            .spawn((
                Pop,
                GridPosition { x: 6, y: 6 },
                Needs {
                    rest: 1.0,
                    ..Default::default()
                },
                PopAction {
                    current: ActionType::Work,
                    ..Default::default()
                },
            ))
            .id();

        world.run_system_once(somnolent_engine_system).unwrap();

        let needs = world.get::<Needs>(pop).unwrap();
        let resources = world.resource::<ColonyResources>();

        assert!(
            (needs.rest - 1.0).abs() < f32::EPSILON,
            "Awake Pop rest should not be drained"
        );
        assert!(
            resources.fuel < f32::EPSILON,
            "No fuel should be generated from awake Pop"
        );
    }

    #[test]
    fn test_somnolent_engine_ignores_far_pops() {
        let mut world = World::new();

        world.insert_resource(ColonyResources {
            fuel: 0.0,
            max_fuel: 100.0,
            ..Default::default()
        });

        world.spawn((DreamDynamo, GridPosition { x: 5, y: 5 }));

        // Pop is sleeping but far away
        let pop = world
            .spawn((
                Pop,
                GridPosition { x: 10, y: 10 }, // Outside Chebyshev distance 3
                Needs {
                    rest: 1.0,
                    ..Default::default()
                },
                PopAction {
                    current: ActionType::SatisfyRest,
                    ..Default::default()
                },
            ))
            .id();

        world.run_system_once(somnolent_engine_system).unwrap();

        let needs = world.get::<Needs>(pop).unwrap();
        let resources = world.resource::<ColonyResources>();

        assert!(
            (needs.rest - 1.0).abs() < f32::EPSILON,
            "Far Pop rest should not be drained"
        );
        assert!(
            resources.fuel < f32::EPSILON,
            "No fuel should be generated from far Pop"
        );
    }
}
