#![allow(clippy::type_complexity)]
//! Storm Thieves (Nova Feature).
//!
//! # The Spark
//! We have `Stowaway`s whose stealth decays over time, and a `WeatherState` that includes `WeatherType::Storm` and `WeatherType::Fog`.
//! We also have a `ClutterGrid` that tracks the messiness of tiles.
//!
//! # The Feature
//! What if Stowaways use the chaos and low visibility of severe weather to their advantage?
//! During a `Storm` or `Fog`, a `Stowaway`'s stealth regenerates (counteracting the normal decay), making them almost impossible to discover.
//! Emboldened by the cover, they recklessly rummage through the building, rapidly generating `Clutter` on the tile they are hiding in.
//!
//! # The Potential
//! This connects the macro-environmental system (Weather) directly to the micro-economic stealth mechanics (Stowaways).
//! Bad weather isn't just a movement penalty anymore; it actively protects parasites hiding in your colony and creates a physical mess (Clutter) that Pops will have to clean up after the storm passes.

use crate::layer1::clutter::ClutterGrid;
use crate::layer1::map::GridPosition;
use crate::layer1::nature::weather::{WeatherState, WeatherType};
use crate::layer1::stowaway::Stowaway;
use bevy_ecs::prelude::*;

const STEALTH_REGEN_RATE: f32 = 0.01;
const STORM_CLUTTER_RATE: f32 = 1.0;

/// System that buffs stowaways during severe weather.
pub fn storm_thieves_system(
    weather: Option<Res<WeatherState>>,
    mut clutter_grid: Option<ResMut<ClutterGrid>>,
    mut stowaways: Query<(&mut Stowaway, &GridPosition)>,
) {
    if let Some(w) = weather {
        if w.current_weather == WeatherType::Storm || w.current_weather == WeatherType::Fog {
            for (mut stowaway, pos) in stowaways.iter_mut() {
                // 1. Regenerate stealth (counteracts the normal decay from discovery_system)
                stowaway.stealth = (stowaway.stealth + STEALTH_REGEN_RATE).min(1.0);

                // 2. Recklessly generate clutter
                if let Some(ref mut grid) = clutter_grid {
                    if pos.x >= 0 && pos.y >= 0 {
                        grid.add_clutter(pos.x as usize, pos.y as usize, STORM_CLUTTER_RATE);
                    }
                }
            }
        }
    }
}

pub fn register(schedule: &mut Schedule) {
    schedule.add_systems(storm_thieves_system);
}

#[cfg(test)]
mod tests {
    use super::*;
    use bevy_ecs::system::RunSystemOnce;

    #[test]
    fn test_storm_thieves_buff_stealth_and_add_clutter() {
        let mut world = World::new();

        world.insert_resource(WeatherState {
            current_weather: WeatherType::Storm,
            duration_remaining: 100,
        });

        let grid = ClutterGrid::new(10, 10);
        world.insert_resource(grid);

        let entity = world
            .spawn((
                Stowaway {
                    stealth: 0.5,
                    hunger: 0.0,
                    last_theft_tick: 0,
                },
                GridPosition { x: 5, y: 5 },
            ))
            .id();

        world.run_system_once(storm_thieves_system).unwrap();

        let stowaway = world.get::<Stowaway>(entity).unwrap();
        assert!(
            stowaway.stealth > 0.5,
            "Stealth should increase during a storm"
        );

        let grid = world.resource::<ClutterGrid>();
        assert!(
            grid.get(5, 5) > 0.0,
            "Clutter should be generated by the reckless stowaway"
        );
    }

    #[test]
    fn test_storm_thieves_inactive_during_clear_weather() {
        let mut world = World::new();

        world.insert_resource(WeatherState {
            current_weather: WeatherType::Clear,
            duration_remaining: 100,
        });

        let grid = ClutterGrid::new(10, 10);
        world.insert_resource(grid);

        let entity = world
            .spawn((
                Stowaway {
                    stealth: 0.5,
                    hunger: 0.0,
                    last_theft_tick: 0,
                },
                GridPosition { x: 5, y: 5 },
            ))
            .id();

        world.run_system_once(storm_thieves_system).unwrap();

        let stowaway = world.get::<Stowaway>(entity).unwrap();
        assert!(
            (stowaway.stealth - 0.5).abs() < f32::EPSILON,
            "Stealth should not change during clear weather"
        );

        let grid = world.resource::<ClutterGrid>();
        assert_eq!(
            grid.get(5, 5),
            0.0,
            "No clutter should be generated during clear weather"
        );
    }
}
