#![allow(clippy::type_complexity)]
//! Stash Clutter (Nova Feature).
//!
//! # The Spark
//! We have Private Stashes for hoarding Pops, Clutter grids for messiness, and Vermin that spawn from resources.
//!
//! # The Feature
//! What if a hoarding Pop generates physical clutter and attracts vermin?
//! This transforms hoarding from a simple resource drain into an active biological and aesthetic hazard.
//! A greedy Pop hiding in a corner will quickly fill their room with trash and rats, forcing the player
//! to inspect them or clean up their mess.

use crate::layer1::clutter::ClutterGrid;
use crate::layer1::map::GridPosition;
use crate::layer1::pop::Pop;
use crate::layer1::private_stash::PrivateStash;
use crate::layer1::vermin::VerminState;
use bevy_ecs::prelude::*;
use rand::Rng;

const HOARDING_THRESHOLD: f32 = 50.0;
const CLUTTER_GENERATION_RATE: f32 = 1.0;
const VERMIN_ATTRACTION_CHANCE: f64 = 0.05;
const VERMIN_SEVERITY_INCREASE: f32 = 1.0;

/// System that adds clutter and vermin based on oversized private stashes.
pub fn stowaway_clutter_system(
    mut clutter_grid: ResMut<ClutterGrid>,
    mut vermin_state_opt: Option<ResMut<VerminState>>,
    mut pops: Query<(&GridPosition, &PrivateStash), With<Pop>>,
    mut log: Option<ResMut<crate::shared::log::MessageLog>>,
) {
    let mut rng = rand::thread_rng();

    for (pos, stash) in pops.iter_mut() {
        let total_stashed: f32 = stash.inventory.values().sum();

        if total_stashed > HOARDING_THRESHOLD {
            // 1. Generate Clutter
            let current_clutter = clutter_grid.get(pos.x as usize, pos.y as usize);
            if current_clutter < 100.0 {
                clutter_grid.add_clutter(pos.x as usize, pos.y as usize, CLUTTER_GENERATION_RATE);
            }

            // 2. Attract Vermin
            if let Some(ref mut vermin_state) = vermin_state_opt {
                if rng.gen_bool(VERMIN_ATTRACTION_CHANCE) {
                    vermin_state.severity = (vermin_state.severity + VERMIN_SEVERITY_INCREASE).min(vermin_state.max_severity);
                    if let Some(ref mut l) = log {
                        l.add_colored(
                            format!(
                                "A massive private stash at ({}, {}) has attracted vermin!",
                                pos.x, pos.y
                            ),
                            ratatui::style::Color::Yellow,
                        );
                    }
                }
            }
        }
    }
}

pub fn register(schedule: &mut Schedule) {
    schedule.add_systems(stowaway_clutter_system);
}

#[cfg(test)]
mod tests {
    use super::*;
    use bevy_ecs::system::RunSystemOnce;
    use crate::layer1::resources::ResourceType;
    use std::collections::HashMap;

    #[test]
    fn test_stowaway_clutter_generates_clutter() {
        let mut world = World::new();

        let clutter_grid = ClutterGrid::new(10, 10);
        world.insert_resource(clutter_grid);

        let mut inventory = HashMap::new();
        inventory.insert(ResourceType::Food, 60.0); // Above 50.0 threshold

        world.spawn((
            Pop,
            GridPosition { x: 5, y: 5 },
            PrivateStash {
                owner: None,
                inventory,
            },
        ));

        world.run_system_once(stowaway_clutter_system).unwrap();

        let clutter_grid = world.resource::<ClutterGrid>();
        assert!(clutter_grid.get(5, 5) > 0.0, "Clutter should be generated by large stash");
    }

    #[test]
    fn test_stowaway_clutter_no_clutter_if_below_threshold() {
        let mut world = World::new();

        let clutter_grid = ClutterGrid::new(10, 10);
        world.insert_resource(clutter_grid);

        let mut inventory = HashMap::new();
        inventory.insert(ResourceType::Food, 40.0); // Below 50.0 threshold

        world.spawn((
            Pop,
            GridPosition { x: 5, y: 5 },
            PrivateStash {
                owner: None,
                inventory,
            },
        ));

        world.run_system_once(stowaway_clutter_system).unwrap();

        let clutter_grid = world.resource::<ClutterGrid>();
        assert_eq!(clutter_grid.get(5, 5), 0.0, "No clutter should be generated by small stash");
    }
}
